// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common-msg.proto

package com.qlangtech.tis.rpc.grpc.log.common;

public interface BuildSharedPhaseStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BuildSharedPhaseStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 allBuildSize = 1;</code>
   */
  long getAllBuildSize();

  /**
   * <code>uint64 buildReaded = 2;</code>
   */
  long getBuildReaded();

  /**
   * <code>uint32 taskid = 3;</code>
   */
  int getTaskid();

  /**
   * <pre>
   * 分组名称
   * </pre>
   *
   * <code>string sharedName = 4;</code>
   */
  java.lang.String getSharedName();
  /**
   * <pre>
   * 分组名称
   * </pre>
   *
   * <code>string sharedName = 4;</code>
   */
  com.google.protobuf.ByteString
      getSharedNameBytes();

  /**
   * <code>bool faild = 5;</code>
   */
  boolean getFaild();

  /**
   * <code>bool complete = 6;</code>
   */
  boolean getComplete();

  /**
   * <code>bool waiting = 7;</code>
   */
  boolean getWaiting();
}
