// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common-msg.proto

package com.qlangtech.tis.rpc.grpc.log.common;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
