// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common-msg.proto

package com.qlangtech.tis.rpc.grpc.log.common;

public interface JoinTaskStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JoinTaskStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string joinTaskName = 1;</code>
   */
  java.lang.String getJoinTaskName();
  /**
   * <code>string joinTaskName = 1;</code>
   */
  com.google.protobuf.ByteString
      getJoinTaskNameBytes();

  /**
   * <code>map&lt;uint32, .JobLog&gt; jobStatus = 2;</code>
   */
  int getJobStatusCount();
  /**
   * <code>map&lt;uint32, .JobLog&gt; jobStatus = 2;</code>
   */
  boolean containsJobStatus(
      int key);
  /**
   * Use {@link #getJobStatusMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.qlangtech.tis.rpc.grpc.log.common.JobLog>
  getJobStatus();
  /**
   * <code>map&lt;uint32, .JobLog&gt; jobStatus = 2;</code>
   */
  java.util.Map<java.lang.Integer, com.qlangtech.tis.rpc.grpc.log.common.JobLog>
  getJobStatusMap();
  /**
   * <code>map&lt;uint32, .JobLog&gt; jobStatus = 2;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.JobLog getJobStatusOrDefault(
      int key,
      com.qlangtech.tis.rpc.grpc.log.common.JobLog defaultValue);
  /**
   * <code>map&lt;uint32, .JobLog&gt; jobStatus = 2;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.JobLog getJobStatusOrThrow(
      int key);

  /**
   * <code>uint32 taskid = 3;</code>
   */
  int getTaskid();

  /**
   * <code>bool faild = 5;</code>
   */
  boolean getFaild();

  /**
   * <code>bool complete = 6;</code>
   */
  boolean getComplete();

  /**
   * <code>bool waiting = 7;</code>
   */
  boolean getWaiting();
}
