// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common-msg.proto

package com.qlangtech.tis.rpc.grpc.log.common;

public interface NodeBackflowStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeBackflowStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeName = 1;</code>
   */
  java.lang.String getNodeName();
  /**
   * <code>string nodeName = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeNameBytes();

  /**
   * <code>uint64 allSize = 2;</code>
   */
  long getAllSize();

  /**
   * <code>uint64 readed = 3;</code>
   */
  long getReaded();

  /**
   * <code>uint32 taskid = 4;</code>
   */
  int getTaskid();

  /**
   * <code>bool faild = 5;</code>
   */
  boolean getFaild();

  /**
   * <code>bool complete = 6;</code>
   */
  boolean getComplete();

  /**
   * <code>bool waiting = 7;</code>
   */
  boolean getWaiting();
}
