// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common-msg.proto

package com.qlangtech.tis.rpc.grpc.log.common;

public interface TableDumpStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TableDumpStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tableName = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string tableName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>uint32 taskid = 2;</code>
   */
  int getTaskid();

  /**
   * <pre>
   * 全部的记录数
   * </pre>
   *
   * <code>uint32 allRows = 3;</code>
   */
  int getAllRows();

  /**
   * <pre>
   * 已经读取的记录数
   * </pre>
   *
   * <code>uint32 readRows = 4;</code>
   */
  int getReadRows();

  /**
   * <code>bool faild = 5;</code>
   */
  boolean getFaild();

  /**
   * <code>bool complete = 6;</code>
   */
  boolean getComplete();

  /**
   * <code>bool waiting = 7;</code>
   */
  boolean getWaiting();
}
