// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incr-status.proto

package com.qlangtech.tis.grpc;

public interface LaunchReportInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.LaunchReportInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .rpc.TopicInfo&gt; collectionFocusTopicInfo = 1;</code>
   */
  int getCollectionFocusTopicInfoCount();
  /**
   * <code>map&lt;string, .rpc.TopicInfo&gt; collectionFocusTopicInfo = 1;</code>
   */
  boolean containsCollectionFocusTopicInfo(
      java.lang.String key);
  /**
   * Use {@link #getCollectionFocusTopicInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.qlangtech.tis.grpc.TopicInfo>
  getCollectionFocusTopicInfo();
  /**
   * <code>map&lt;string, .rpc.TopicInfo&gt; collectionFocusTopicInfo = 1;</code>
   */
  java.util.Map<java.lang.String, com.qlangtech.tis.grpc.TopicInfo>
  getCollectionFocusTopicInfoMap();
  /**
   * <code>map&lt;string, .rpc.TopicInfo&gt; collectionFocusTopicInfo = 1;</code>
   */

  com.qlangtech.tis.grpc.TopicInfo getCollectionFocusTopicInfoOrDefault(
      java.lang.String key,
      com.qlangtech.tis.grpc.TopicInfo defaultValue);
  /**
   * <code>map&lt;string, .rpc.TopicInfo&gt; collectionFocusTopicInfo = 1;</code>
   */

  com.qlangtech.tis.grpc.TopicInfo getCollectionFocusTopicInfoOrThrow(
      java.lang.String key);
}
