// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incr-status.proto

package com.qlangtech.tis.grpc;

public interface LaunchReportInfoEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.LaunchReportInfoEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *topic
   * </pre>
   *
   * <code>string topicName = 1;</code>
   */
  java.lang.String getTopicName();
  /**
   * <pre>
   *topic
   * </pre>
   *
   * <code>string topicName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();

  /**
   * <pre>
   *tags
   * </pre>
   *
   * <code>repeated string tagName = 2;</code>
   */
  java.util.List<java.lang.String>
      getTagNameList();
  /**
   * <pre>
   *tags
   * </pre>
   *
   * <code>repeated string tagName = 2;</code>
   */
  int getTagNameCount();
  /**
   * <pre>
   *tags
   * </pre>
   *
   * <code>repeated string tagName = 2;</code>
   */
  java.lang.String getTagName(int index);
  /**
   * <pre>
   *tags
   * </pre>
   *
   * <code>repeated string tagName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagNameBytes(int index);
}
