// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incr-status.proto

package com.qlangtech.tis.grpc;

public interface MasterJobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.MasterJob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rpc.MasterJob.JobType jobType = 1;</code>
   */
  int getJobTypeValue();
  /**
   * <code>.rpc.MasterJob.JobType jobType = 1;</code>
   */
  com.qlangtech.tis.grpc.MasterJob.JobType getJobType();

  /**
   * <code>bool stop = 2;</code>
   */
  boolean getStop();

  /**
   * <code>string indexName = 3;</code>
   */
  java.lang.String getIndexName();
  /**
   * <code>string indexName = 3;</code>
   */
  com.google.protobuf.ByteString
      getIndexNameBytes();

  /**
   * <code>string uuid = 4;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 4;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>uint64 createTime = 5;</code>
   */
  long getCreateTime();
}
