// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incr-status.proto

package com.qlangtech.tis.grpc;

public interface TableSingleDataIndexStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.TableSingleDataIndexStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, uint64&gt; tableConsumeData = 1;</code>
   */
  int getTableConsumeDataCount();
  /**
   * <code>map&lt;string, uint64&gt; tableConsumeData = 1;</code>
   */
  boolean containsTableConsumeData(
      java.lang.String key);
  /**
   * Use {@link #getTableConsumeDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getTableConsumeData();
  /**
   * <code>map&lt;string, uint64&gt; tableConsumeData = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getTableConsumeDataMap();
  /**
   * <code>map&lt;string, uint64&gt; tableConsumeData = 1;</code>
   */

  long getTableConsumeDataOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <code>map&lt;string, uint64&gt; tableConsumeData = 1;</code>
   */

  long getTableConsumeDataOrThrow(
      java.lang.String key);

  /**
   * <code>uint32 bufferQueueRemainingCapacity = 2;</code>
   */
  int getBufferQueueRemainingCapacity();

  /**
   * <code>uint32 bufferQueueUsedSize = 3;</code>
   */
  int getBufferQueueUsedSize();

  /**
   * <code>uint32 consumeErrorCount = 4;</code>
   */
  int getConsumeErrorCount();

  /**
   * <code>uint32 ignoreRowsCount = 5;</code>
   */
  int getIgnoreRowsCount();

  /**
   * <code>string uuid = 6;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 6;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>uint64 tis30sAvgRT = 7;</code>
   */
  long getTis30SAvgRT();

  /**
   * <pre>
   * 增量任务执行是否暂停
   * </pre>
   *
   * <code>bool incrProcessPaused = 8;</code>
   */
  boolean getIncrProcessPaused();
}
