// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incr-status.proto

package com.qlangtech.tis.grpc;

public interface TopicInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.TopicInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rpc.LaunchReportInfoEntry topicWithTags = 1;</code>
   */
  java.util.List<com.qlangtech.tis.grpc.LaunchReportInfoEntry> 
      getTopicWithTagsList();
  /**
   * <code>repeated .rpc.LaunchReportInfoEntry topicWithTags = 1;</code>
   */
  com.qlangtech.tis.grpc.LaunchReportInfoEntry getTopicWithTags(int index);
  /**
   * <code>repeated .rpc.LaunchReportInfoEntry topicWithTags = 1;</code>
   */
  int getTopicWithTagsCount();
  /**
   * <code>repeated .rpc.LaunchReportInfoEntry topicWithTags = 1;</code>
   */
  java.util.List<? extends com.qlangtech.tis.grpc.LaunchReportInfoEntryOrBuilder> 
      getTopicWithTagsOrBuilderList();
  /**
   * <code>repeated .rpc.LaunchReportInfoEntry topicWithTags = 1;</code>
   */
  com.qlangtech.tis.grpc.LaunchReportInfoEntryOrBuilder getTopicWithTagsOrBuilder(
      int index);
}
