// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incr-status.proto

package com.qlangtech.tis.grpc;

public interface UpdateCounterMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.UpdateCounterMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .rpc.TableSingleDataIndexStatus&gt; data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, .rpc.TableSingleDataIndexStatus&gt; data = 1;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.qlangtech.tis.grpc.TableSingleDataIndexStatus>
  getData();
  /**
   * <code>map&lt;string, .rpc.TableSingleDataIndexStatus&gt; data = 1;</code>
   */
  java.util.Map<java.lang.String, com.qlangtech.tis.grpc.TableSingleDataIndexStatus>
  getDataMap();
  /**
   * <code>map&lt;string, .rpc.TableSingleDataIndexStatus&gt; data = 1;</code>
   */

  com.qlangtech.tis.grpc.TableSingleDataIndexStatus getDataOrDefault(
      java.lang.String key,
      com.qlangtech.tis.grpc.TableSingleDataIndexStatus defaultValue);
  /**
   * <code>map&lt;string, .rpc.TableSingleDataIndexStatus&gt; data = 1;</code>
   */

  com.qlangtech.tis.grpc.TableSingleDataIndexStatus getDataOrThrow(
      java.lang.String key);

  /**
   * <code>uint64 gcCounter = 2;</code>
   */
  long getGcCounter();

  /**
   * <pre>
   * 从哪个地址发送过来的
   * </pre>
   *
   * <code>string from = 3;</code>
   */
  java.lang.String getFrom();
  /**
   * <pre>
   * 从哪个地址发送过来的
   * </pre>
   *
   * <code>string from = 3;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>uint64 updateTime = 4;</code>
   */
  long getUpdateTime();
}
