// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PBuildPhaseStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PBuildPhaseStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .BuildSharedPhaseStatus&gt; nodeBuildStatus = 1;</code>
   */
  int getNodeBuildStatusCount();
  /**
   * <code>map&lt;string, .BuildSharedPhaseStatus&gt; nodeBuildStatus = 1;</code>
   */
  boolean containsNodeBuildStatus(
      java.lang.String key);
  /**
   * Use {@link #getNodeBuildStatusMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.BuildSharedPhaseStatus>
  getNodeBuildStatus();
  /**
   * <code>map&lt;string, .BuildSharedPhaseStatus&gt; nodeBuildStatus = 1;</code>
   */
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.BuildSharedPhaseStatus>
  getNodeBuildStatusMap();
  /**
   * <code>map&lt;string, .BuildSharedPhaseStatus&gt; nodeBuildStatus = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.BuildSharedPhaseStatus getNodeBuildStatusOrDefault(
      java.lang.String key,
      com.qlangtech.tis.rpc.grpc.log.common.BuildSharedPhaseStatus defaultValue);
  /**
   * <code>map&lt;string, .BuildSharedPhaseStatus&gt; nodeBuildStatus = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.BuildSharedPhaseStatus getNodeBuildStatusOrThrow(
      java.lang.String key);
}
