// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PBuildPhaseStatusParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PBuildPhaseStatusParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 taskid = 1;</code>
   */
  long getTaskid();
}
