// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PDumpPhaseStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PDumpPhaseStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .TableDumpStatus&gt; tablesDump = 1;</code>
   */
  int getTablesDumpCount();
  /**
   * <code>map&lt;string, .TableDumpStatus&gt; tablesDump = 1;</code>
   */
  boolean containsTablesDump(
      java.lang.String key);
  /**
   * Use {@link #getTablesDumpMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.TableDumpStatus>
  getTablesDump();
  /**
   * <code>map&lt;string, .TableDumpStatus&gt; tablesDump = 1;</code>
   */
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.TableDumpStatus>
  getTablesDumpMap();
  /**
   * <code>map&lt;string, .TableDumpStatus&gt; tablesDump = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.TableDumpStatus getTablesDumpOrDefault(
      java.lang.String key,
      com.qlangtech.tis.rpc.grpc.log.common.TableDumpStatus defaultValue);
  /**
   * <code>map&lt;string, .TableDumpStatus&gt; tablesDump = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.TableDumpStatus getTablesDumpOrThrow(
      java.lang.String key);
}
