// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PExecuteStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PExecuteState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.stream.PExecuteState.InfoType infoType = 1;</code>
   */
  int getInfoTypeValue();
  /**
   * <code>.stream.PExecuteState.InfoType infoType = 1;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PExecuteState.InfoType getInfoType();

  /**
   * <code>.stream.PExecuteState.LogType logType = 2;</code>
   */
  int getLogTypeValue();
  /**
   * <code>.stream.PExecuteState.LogType logType = 2;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PExecuteState.LogType getLogType();

  /**
   * <code>string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string from = 4;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 4;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>uint64 jobId = 5;</code>
   */
  long getJobId();

  /**
   * <code>uint64 taskId = 6;</code>
   */
  long getTaskId();

  /**
   * <code>string serviceName = 7;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 7;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string execState = 8;</code>
   */
  java.lang.String getExecState();
  /**
   * <code>string execState = 8;</code>
   */
  com.google.protobuf.ByteString
      getExecStateBytes();

  /**
   * <code>uint64 time = 9;</code>
   */
  long getTime();

  /**
   * <code>string component = 10;</code>
   */
  java.lang.String getComponent();
  /**
   * <code>string component = 10;</code>
   */
  com.google.protobuf.ByteString
      getComponentBytes();
}
