// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PIndexBackFlowPhaseStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PIndexBackFlowPhaseStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .NodeBackflowStatus&gt; nodesStatus = 1;</code>
   */
  int getNodesStatusCount();
  /**
   * <code>map&lt;string, .NodeBackflowStatus&gt; nodesStatus = 1;</code>
   */
  boolean containsNodesStatus(
      java.lang.String key);
  /**
   * Use {@link #getNodesStatusMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.NodeBackflowStatus>
  getNodesStatus();
  /**
   * <code>map&lt;string, .NodeBackflowStatus&gt; nodesStatus = 1;</code>
   */
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.NodeBackflowStatus>
  getNodesStatusMap();
  /**
   * <code>map&lt;string, .NodeBackflowStatus&gt; nodesStatus = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.NodeBackflowStatus getNodesStatusOrDefault(
      java.lang.String key,
      com.qlangtech.tis.rpc.grpc.log.common.NodeBackflowStatus defaultValue);
  /**
   * <code>map&lt;string, .NodeBackflowStatus&gt; nodesStatus = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.NodeBackflowStatus getNodesStatusOrThrow(
      java.lang.String key);
}
