// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PJoinPhaseStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PJoinPhaseStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .JoinTaskStatus&gt; taskStatus = 1;</code>
   */
  int getTaskStatusCount();
  /**
   * <code>map&lt;string, .JoinTaskStatus&gt; taskStatus = 1;</code>
   */
  boolean containsTaskStatus(
      java.lang.String key);
  /**
   * Use {@link #getTaskStatusMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.JoinTaskStatus>
  getTaskStatus();
  /**
   * <code>map&lt;string, .JoinTaskStatus&gt; taskStatus = 1;</code>
   */
  java.util.Map<java.lang.String, com.qlangtech.tis.rpc.grpc.log.common.JoinTaskStatus>
  getTaskStatusMap();
  /**
   * <code>map&lt;string, .JoinTaskStatus&gt; taskStatus = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.JoinTaskStatus getTaskStatusOrDefault(
      java.lang.String key,
      com.qlangtech.tis.rpc.grpc.log.common.JoinTaskStatus defaultValue);
  /**
   * <code>map&lt;string, .JoinTaskStatus&gt; taskStatus = 1;</code>
   */

  com.qlangtech.tis.rpc.grpc.log.common.JoinTaskStatus getTaskStatusOrThrow(
      java.lang.String key);
}
