// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PMonotorTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PMonotorTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string collection = 1;</code>
   */
  java.lang.String getCollection();
  /**
   * <code>string collection = 1;</code>
   */
  com.google.protobuf.ByteString
      getCollectionBytes();

  /**
   * <code>uint32 taskid = 2;</code>
   */
  int getTaskid();

  /**
   * <code>.stream.PExecuteState.LogType logtype = 3;</code>
   */
  int getLogtypeValue();
  /**
   * <code>.stream.PExecuteState.LogType logtype = 3;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PExecuteState.LogType getLogtype();
}
