// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PPhaseStatusCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PPhaseStatusCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.stream.PDumpPhaseStatus dumpPhase = 1;</code>
   */
  boolean hasDumpPhase();
  /**
   * <code>.stream.PDumpPhaseStatus dumpPhase = 1;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PDumpPhaseStatus getDumpPhase();
  /**
   * <code>.stream.PDumpPhaseStatus dumpPhase = 1;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PDumpPhaseStatusOrBuilder getDumpPhaseOrBuilder();

  /**
   * <code>.stream.PJoinPhaseStatus joinPhase = 2;</code>
   */
  boolean hasJoinPhase();
  /**
   * <code>.stream.PJoinPhaseStatus joinPhase = 2;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PJoinPhaseStatus getJoinPhase();
  /**
   * <code>.stream.PJoinPhaseStatus joinPhase = 2;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PJoinPhaseStatusOrBuilder getJoinPhaseOrBuilder();

  /**
   * <code>.stream.PBuildPhaseStatus buildPhase = 3;</code>
   */
  boolean hasBuildPhase();
  /**
   * <code>.stream.PBuildPhaseStatus buildPhase = 3;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PBuildPhaseStatus getBuildPhase();
  /**
   * <code>.stream.PBuildPhaseStatus buildPhase = 3;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PBuildPhaseStatusOrBuilder getBuildPhaseOrBuilder();

  /**
   * <code>.stream.PIndexBackFlowPhaseStatus indexBackFlowPhaseStatus = 4;</code>
   */
  boolean hasIndexBackFlowPhaseStatus();
  /**
   * <code>.stream.PIndexBackFlowPhaseStatus indexBackFlowPhaseStatus = 4;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PIndexBackFlowPhaseStatus getIndexBackFlowPhaseStatus();
  /**
   * <code>.stream.PIndexBackFlowPhaseStatus indexBackFlowPhaseStatus = 4;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.stream.PIndexBackFlowPhaseStatusOrBuilder getIndexBackFlowPhaseStatusOrBuilder();

  /**
   * <code>uint32 taskId = 5;</code>
   */
  int getTaskId();
}
