// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log-collector.proto

package com.qlangtech.tis.rpc.grpc.log.stream;

public interface PSynResTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PSynResTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   **
   * dataX pipeline OR transform workflow
   * </pre>
   *
   * <code>bool pipeline = 2;</code>
   */
  boolean getPipeline();
}
