// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logger-appender.proto

package com.qlangtech.tis.rpc.grpc.log.appender;

public final class LogAppenderService {
  private LogAppenderService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_LoggingEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_LoggingEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_LoggingEvent_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_LoggingEvent_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025logger-appender.proto\022\006stream\032\020common-" +
      "msg.proto\"\200\001\n\014LoggingEvent\0222\n\007headers\030\001 " +
      "\003(\0132!.stream.LoggingEvent.HeadersEntry\022\014" +
      "\n\004body\030\002 \001(\t\032.\n\014HeadersEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\00127\n\013LogAppender\022(\n\006A" +
      "ppend\022\024.stream.LoggingEvent\032\006.Empty\"\000BF\n" +
      "\'com.qlangtech.tis.rpc.grpc.log.appender" +
      "B\022LogAppenderServiceP\001\242\002\004HLWSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.qlangtech.tis.rpc.grpc.log.common.LogCollectorProto.getDescriptor(),
        }, assigner);
    internal_static_stream_LoggingEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stream_LoggingEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_LoggingEvent_descriptor,
        new java.lang.String[] { "Headers", "Body", });
    internal_static_stream_LoggingEvent_HeadersEntry_descriptor =
      internal_static_stream_LoggingEvent_descriptor.getNestedTypes().get(0);
    internal_static_stream_LoggingEvent_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_LoggingEvent_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.qlangtech.tis.rpc.grpc.log.common.LogCollectorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
