// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logger-appender.proto

package com.qlangtech.tis.rpc.grpc.log.appender;

public interface LoggingEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.LoggingEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  int getHeadersCount();
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  boolean containsHeaders(
      java.lang.String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaders();
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeadersMap();
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */

  java.lang.String getHeadersOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; headers = 1;</code>
   */

  java.lang.String getHeadersOrThrow(
      java.lang.String key);

  /**
   * <code>string body = 2;</code>
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>.stream.LoggingEvent.Level level = 3;</code>
   */
  int getLevelValue();
  /**
   * <code>.stream.LoggingEvent.Level level = 3;</code>
   */
  com.qlangtech.tis.rpc.grpc.log.appender.LoggingEvent.Level getLevel();
}
