// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public final class DataXRecordsPreviewService {
  private DataXRecordsPreviewService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_PreviewRowsDataCriteria_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_PreviewRowsDataCriteria_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_PreviewRowsDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_PreviewRowsDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_PreviewRowsDataResponse_ColumnHeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_PreviewRowsDataResponse_ColumnHeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_HeaderColGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_HeaderColGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_Record_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_StringValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_StringValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_OffsetColValGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_OffsetColValGrpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033preview-datax-records.proto\022\006stream\"\216\001" +
      "\n\027PreviewRowsDataCriteria\022\021\n\tdataXName\030\001" +
      " \001(\t\022\021\n\ttableName\030\002 \001(\t\022\014\n\004next\030\003 \001(\010\022-\n" +
      "\013orderByCols\030\004 \003(\0132\030.stream.OffsetColVal" +
      "Grpc\022\020\n\010pageSize\030\005 \001(\r\"\257\002\n\027PreviewRowsDa" +
      "taResponse\022G\n\014columnHeader\030\001 \003(\01321.strea" +
      "m.PreviewRowsDataResponse.ColumnHeaderEn" +
      "try\022\037\n\007records\030\002 \003(\0132\016.stream.Record\022.\n\014" +
      "headerCursor\030\003 \003(\0132\030.stream.OffsetColVal" +
      "Grpc\022.\n\014tailerCursor\030\004 \003(\0132\030.stream.Offs" +
      "etColValGrpc\032J\n\021ColumnHeaderEntry\022\013\n\003key" +
      "\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.stream.HeaderCol" +
      "Grpc:\0028\001\",\n\rHeaderColGrpc\022\r\n\005index\030\001 \001(\r" +
      "\022\014\n\004blob\030\002 \001(\010\".\n\006Record\022$\n\007colVals\030\001 \003(" +
      "\0132\023.stream.StringValue\"\'\n\013StringValue\022\013\n" +
      "\003val\030\001 \001(\t\022\013\n\003nil\030\002 \001(\010\"H\n\020OffsetColValG" +
      "rpc\022\016\n\006colKey\030\001 \001(\t\022\013\n\003val\030\002 \001(\t\022\027\n\017nume" +
      "ricJdbcType\030\003 \001(\0102l\n\023DataXRecordsPreview" +
      "\022U\n\017previewRowsData\022\037.stream.PreviewRows" +
      "DataCriteria\032\037.stream.PreviewRowsDataRes" +
      "ponse\"\000BO\n(com.qlangtech.tis.rpc.grpc.da" +
      "tax.previewB\032DataXRecordsPreviewServiceP" +
      "\001\242\002\004HLWSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_stream_PreviewRowsDataCriteria_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stream_PreviewRowsDataCriteria_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_PreviewRowsDataCriteria_descriptor,
        new java.lang.String[] { "DataXName", "TableName", "Next", "OrderByCols", "PageSize", });
    internal_static_stream_PreviewRowsDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stream_PreviewRowsDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_PreviewRowsDataResponse_descriptor,
        new java.lang.String[] { "ColumnHeader", "Records", "HeaderCursor", "TailerCursor", });
    internal_static_stream_PreviewRowsDataResponse_ColumnHeaderEntry_descriptor =
      internal_static_stream_PreviewRowsDataResponse_descriptor.getNestedTypes().get(0);
    internal_static_stream_PreviewRowsDataResponse_ColumnHeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_PreviewRowsDataResponse_ColumnHeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_stream_HeaderColGrpc_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stream_HeaderColGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_HeaderColGrpc_descriptor,
        new java.lang.String[] { "Index", "Blob", });
    internal_static_stream_Record_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stream_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_Record_descriptor,
        new java.lang.String[] { "ColVals", });
    internal_static_stream_StringValue_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_stream_StringValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_StringValue_descriptor,
        new java.lang.String[] { "Val", "Nil", });
    internal_static_stream_OffsetColValGrpc_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_stream_OffsetColValGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_OffsetColValGrpc_descriptor,
        new java.lang.String[] { "ColKey", "Val", "NumericJdbcType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
