// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public interface HeaderColGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.HeaderColGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 index = 1;</code>
   */
  int getIndex();

  /**
   * <code>bool blob = 2;</code>
   */
  boolean getBlob();
}
