// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public interface OffsetColValGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.OffsetColValGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string colKey = 1;</code>
   */
  java.lang.String getColKey();
  /**
   * <code>string colKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getColKeyBytes();

  /**
   * <code>string val = 2;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 2;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();

  /**
   * <code>bool numericJdbcType = 3;</code>
   */
  boolean getNumericJdbcType();
}
