// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public interface PreviewRowsDataCriteriaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PreviewRowsDataCriteria)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataXName = 1;</code>
   */
  java.lang.String getDataXName();
  /**
   * <code>string dataXName = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataXNameBytes();

  /**
   * <code>string tableName = 2;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string tableName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>bool next = 3;</code>
   */
  boolean getNext();

  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */
  int getOrderByColsCount();
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */
  boolean containsOrderByCols(
      java.lang.String key);
  /**
   * Use {@link #getOrderByColsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getOrderByCols();
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getOrderByColsMap();
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */

  java.lang.String getOrderByColsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */

  java.lang.String getOrderByColsOrThrow(
      java.lang.String key);

  /**
   * <code>uint32 pageSize = 5;</code>
   */
  int getPageSize();
}
