// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

/**
 * Protobuf type {@code stream.PreviewRowsDataResponse}
 */
public  final class PreviewRowsDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stream.PreviewRowsDataResponse)
    PreviewRowsDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PreviewRowsDataResponse.newBuilder() to construct.
  private PreviewRowsDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PreviewRowsDataResponse() {
    records_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PreviewRowsDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              columnHeader_ = com.google.protobuf.MapField.newMapField(
                  ColumnHeaderDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
            columnHeader__ = input.readMessage(
                ColumnHeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            columnHeader_.getMutableMap().put(
                columnHeader__.getKey(), columnHeader__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              records_ = new java.util.ArrayList<com.qlangtech.tis.rpc.grpc.datax.preview.Record>();
              mutable_bitField0_ |= 0x00000002;
            }
            records_.add(
                input.readMessage(com.qlangtech.tis.rpc.grpc.datax.preview.Record.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        records_ = java.util.Collections.unmodifiableList(records_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetColumnHeader();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse.class, com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse.Builder.class);
  }

  public static final int COLUMNHEADER_FIELD_NUMBER = 1;
  private static final class ColumnHeaderDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataResponse_ColumnHeaderEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> columnHeader_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetColumnHeader() {
    if (columnHeader_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ColumnHeaderDefaultEntryHolder.defaultEntry);
    }
    return columnHeader_;
  }

  public int getColumnHeaderCount() {
    return internalGetColumnHeader().getMap().size();
  }
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */

  public boolean containsColumnHeader(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetColumnHeader().getMap().containsKey(key);
  }
  /**
   * Use {@link #getColumnHeaderMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer> getColumnHeader() {
    return getColumnHeaderMap();
  }
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.Integer> getColumnHeaderMap() {
    return internalGetColumnHeader().getMap();
  }
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */

  public int getColumnHeaderOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetColumnHeader().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */

  public int getColumnHeaderOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetColumnHeader().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int RECORDS_FIELD_NUMBER = 2;
  private java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.Record> records_;
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  public java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.Record> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  public java.util.List<? extends com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder> 
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  public com.qlangtech.tis.rpc.grpc.datax.preview.Record getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  public com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetColumnHeader(),
        ColumnHeaderDefaultEntryHolder.defaultEntry,
        1);
    for (int i = 0; i < records_.size(); i++) {
      output.writeMessage(2, records_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetColumnHeader().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      columnHeader__ = ColumnHeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, columnHeader__);
    }
    for (int i = 0; i < records_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, records_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse)) {
      return super.equals(obj);
    }
    com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse other = (com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse) obj;

    if (!internalGetColumnHeader().equals(
        other.internalGetColumnHeader())) return false;
    if (!getRecordsList()
        .equals(other.getRecordsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetColumnHeader().getMap().isEmpty()) {
      hash = (37 * hash) + COLUMNHEADER_FIELD_NUMBER;
      hash = (53 * hash) + internalGetColumnHeader().hashCode();
    }
    if (getRecordsCount() > 0) {
      hash = (37 * hash) + RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stream.PreviewRowsDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stream.PreviewRowsDataResponse)
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetColumnHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableColumnHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse.class, com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse.Builder.class);
    }

    // Construct using com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecordsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableColumnHeader().clear();
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataResponse_descriptor;
    }

    @java.lang.Override
    public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse getDefaultInstanceForType() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse build() {
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse buildPartial() {
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse result = new com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse(this);
      int from_bitField0_ = bitField0_;
      result.columnHeader_ = internalGetColumnHeader();
      result.columnHeader_.makeImmutable();
      if (recordsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          records_ = java.util.Collections.unmodifiableList(records_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.records_ = records_;
      } else {
        result.records_ = recordsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse) {
        return mergeFrom((com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse other) {
      if (other == com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse.getDefaultInstance()) return this;
      internalGetMutableColumnHeader().mergeFrom(
          other.internalGetColumnHeader());
      if (recordsBuilder_ == null) {
        if (!other.records_.isEmpty()) {
          if (records_.isEmpty()) {
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRecordsIsMutable();
            records_.addAll(other.records_);
          }
          onChanged();
        }
      } else {
        if (!other.records_.isEmpty()) {
          if (recordsBuilder_.isEmpty()) {
            recordsBuilder_.dispose();
            recordsBuilder_ = null;
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000002);
            recordsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecordsFieldBuilder() : null;
          } else {
            recordsBuilder_.addAllMessages(other.records_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> columnHeader_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetColumnHeader() {
      if (columnHeader_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ColumnHeaderDefaultEntryHolder.defaultEntry);
      }
      return columnHeader_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetMutableColumnHeader() {
      onChanged();;
      if (columnHeader_ == null) {
        columnHeader_ = com.google.protobuf.MapField.newMapField(
            ColumnHeaderDefaultEntryHolder.defaultEntry);
      }
      if (!columnHeader_.isMutable()) {
        columnHeader_ = columnHeader_.copy();
      }
      return columnHeader_;
    }

    public int getColumnHeaderCount() {
      return internalGetColumnHeader().getMap().size();
    }
    /**
     * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
     */

    public boolean containsColumnHeader(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetColumnHeader().getMap().containsKey(key);
    }
    /**
     * Use {@link #getColumnHeaderMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getColumnHeader() {
      return getColumnHeaderMap();
    }
    /**
     * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getColumnHeaderMap() {
      return internalGetColumnHeader().getMap();
    }
    /**
     * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
     */

    public int getColumnHeaderOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetColumnHeader().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
     */

    public int getColumnHeaderOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetColumnHeader().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearColumnHeader() {
      internalGetMutableColumnHeader().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
     */

    public Builder removeColumnHeader(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableColumnHeader().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getMutableColumnHeader() {
      return internalGetMutableColumnHeader().getMutableMap();
    }
    /**
     * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
     */
    public Builder putColumnHeader(
        java.lang.String key,
        int value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      internalGetMutableColumnHeader().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
     */

    public Builder putAllColumnHeader(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      internalGetMutableColumnHeader().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.Record> records_ =
      java.util.Collections.emptyList();
    private void ensureRecordsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        records_ = new java.util.ArrayList<com.qlangtech.tis.rpc.grpc.datax.preview.Record>(records_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.qlangtech.tis.rpc.grpc.datax.preview.Record, com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder, com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder> recordsBuilder_;

    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.Record> getRecordsList() {
      if (recordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(records_);
      } else {
        return recordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public int getRecordsCount() {
      if (recordsBuilder_ == null) {
        return records_.size();
      } else {
        return recordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public com.qlangtech.tis.rpc.grpc.datax.preview.Record getRecords(int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);
      } else {
        return recordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder setRecords(
        int index, com.qlangtech.tis.rpc.grpc.datax.preview.Record value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.set(index, value);
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder setRecords(
        int index, com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder addRecords(com.qlangtech.tis.rpc.grpc.datax.preview.Record value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder addRecords(
        int index, com.qlangtech.tis.rpc.grpc.datax.preview.Record value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(index, value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder addRecords(
        com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder addRecords(
        int index, com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends com.qlangtech.tis.rpc.grpc.datax.preview.Record> values) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, records_);
        onChanged();
      } else {
        recordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder clearRecords() {
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public Builder removeRecords(int index) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.remove(index);
        onChanged();
      } else {
        recordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder getRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder getRecordsOrBuilder(
        int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);  } else {
        return recordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public java.util.List<? extends com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder> 
         getRecordsOrBuilderList() {
      if (recordsBuilder_ != null) {
        return recordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(records_);
      }
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder addRecordsBuilder() {
      return getRecordsFieldBuilder().addBuilder(
          com.qlangtech.tis.rpc.grpc.datax.preview.Record.getDefaultInstance());
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder addRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().addBuilder(
          index, com.qlangtech.tis.rpc.grpc.datax.preview.Record.getDefaultInstance());
    }
    /**
     * <code>repeated .stream.Record records = 2;</code>
     */
    public java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder> 
         getRecordsBuilderList() {
      return getRecordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.qlangtech.tis.rpc.grpc.datax.preview.Record, com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder, com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder> 
        getRecordsFieldBuilder() {
      if (recordsBuilder_ == null) {
        recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.qlangtech.tis.rpc.grpc.datax.preview.Record, com.qlangtech.tis.rpc.grpc.datax.preview.Record.Builder, com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder>(
                records_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        records_ = null;
      }
      return recordsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stream.PreviewRowsDataResponse)
  }

  // @@protoc_insertion_point(class_scope:stream.PreviewRowsDataResponse)
  private static final com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse();
  }

  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PreviewRowsDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<PreviewRowsDataResponse>() {
    @java.lang.Override
    public PreviewRowsDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PreviewRowsDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PreviewRowsDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreviewRowsDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

