// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public interface PreviewRowsDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PreviewRowsDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */
  int getColumnHeaderCount();
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */
  boolean containsColumnHeader(
      java.lang.String key);
  /**
   * Use {@link #getColumnHeaderMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getColumnHeader();
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getColumnHeaderMap();
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */

  int getColumnHeaderOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, uint32&gt; columnHeader = 1;</code>
   */

  int getColumnHeaderOrThrow(
      java.lang.String key);

  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.Record> 
      getRecordsList();
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  com.qlangtech.tis.rpc.grpc.datax.preview.Record getRecords(int index);
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  java.util.List<? extends com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .stream.Record records = 2;</code>
   */
  com.qlangtech.tis.rpc.grpc.datax.preview.RecordOrBuilder getRecordsOrBuilder(
      int index);
}
