// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

/**
 * Protobuf type {@code stream.PreviewRowsDataCriteria}
 */
public  final class PreviewRowsDataCriteria extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stream.PreviewRowsDataCriteria)
    PreviewRowsDataCriteriaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PreviewRowsDataCriteria.newBuilder() to construct.
  private PreviewRowsDataCriteria(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PreviewRowsDataCriteria() {
    dataXName_ = "";
    tableName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PreviewRowsDataCriteria(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dataXName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 24: {

            next_ = input.readBool();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              orderByCols_ = com.google.protobuf.MapField.newMapField(
                  OrderByColsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            orderByCols__ = input.readMessage(
                OrderByColsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            orderByCols_.getMutableMap().put(
                orderByCols__.getKey(), orderByCols__.getValue());
            break;
          }
          case 40: {

            pageSize_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataCriteria_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetOrderByCols();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataCriteria_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria.class, com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria.Builder.class);
  }

  private int bitField0_;
  public static final int DATAXNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object dataXName_;
  /**
   * <code>string dataXName = 1;</code>
   */
  public java.lang.String getDataXName() {
    java.lang.Object ref = dataXName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataXName_ = s;
      return s;
    }
  }
  /**
   * <code>string dataXName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDataXNameBytes() {
    java.lang.Object ref = dataXName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataXName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object tableName_;
  /**
   * <code>string tableName = 2;</code>
   */
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string tableName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEXT_FIELD_NUMBER = 3;
  private boolean next_;
  /**
   * <code>bool next = 3;</code>
   */
  public boolean getNext() {
    return next_;
  }

  public static final int ORDERBYCOLS_FIELD_NUMBER = 4;
  private static final class OrderByColsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataCriteria_OrderByColsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> orderByCols_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetOrderByCols() {
    if (orderByCols_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          OrderByColsDefaultEntryHolder.defaultEntry);
    }
    return orderByCols_;
  }

  public int getOrderByColsCount() {
    return internalGetOrderByCols().getMap().size();
  }
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */

  public boolean containsOrderByCols(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetOrderByCols().getMap().containsKey(key);
  }
  /**
   * Use {@link #getOrderByColsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getOrderByCols() {
    return getOrderByColsMap();
  }
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getOrderByColsMap() {
    return internalGetOrderByCols().getMap();
  }
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */

  public java.lang.String getOrderByColsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetOrderByCols().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>map&lt;string, string&gt; orderByCols = 4;</code>
   */

  public java.lang.String getOrderByColsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetOrderByCols().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PAGESIZE_FIELD_NUMBER = 5;
  private int pageSize_;
  /**
   * <code>uint32 pageSize = 5;</code>
   */
  public int getPageSize() {
    return pageSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDataXNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataXName_);
    }
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableName_);
    }
    if (next_ != false) {
      output.writeBool(3, next_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetOrderByCols(),
        OrderByColsDefaultEntryHolder.defaultEntry,
        4);
    if (pageSize_ != 0) {
      output.writeUInt32(5, pageSize_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDataXNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataXName_);
    }
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableName_);
    }
    if (next_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, next_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetOrderByCols().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      orderByCols__ = OrderByColsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, orderByCols__);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, pageSize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria)) {
      return super.equals(obj);
    }
    com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria other = (com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria) obj;

    if (!getDataXName()
        .equals(other.getDataXName())) return false;
    if (!getTableName()
        .equals(other.getTableName())) return false;
    if (getNext()
        != other.getNext()) return false;
    if (!internalGetOrderByCols().equals(
        other.internalGetOrderByCols())) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATAXNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDataXName().hashCode();
    hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + NEXT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNext());
    if (!internalGetOrderByCols().getMap().isEmpty()) {
      hash = (37 * hash) + ORDERBYCOLS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetOrderByCols().hashCode();
    }
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stream.PreviewRowsDataCriteria}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stream.PreviewRowsDataCriteria)
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteriaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataCriteria_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetOrderByCols();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableOrderByCols();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataCriteria_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria.class, com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria.Builder.class);
    }

    // Construct using com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dataXName_ = "";

      tableName_ = "";

      next_ = false;

      internalGetMutableOrderByCols().clear();
      pageSize_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.DataXRecordsPreviewService.internal_static_stream_PreviewRowsDataCriteria_descriptor;
    }

    @java.lang.Override
    public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria getDefaultInstanceForType() {
      return com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria.getDefaultInstance();
    }

    @java.lang.Override
    public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria build() {
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria buildPartial() {
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria result = new com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.dataXName_ = dataXName_;
      result.tableName_ = tableName_;
      result.next_ = next_;
      result.orderByCols_ = internalGetOrderByCols();
      result.orderByCols_.makeImmutable();
      result.pageSize_ = pageSize_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria) {
        return mergeFrom((com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria other) {
      if (other == com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria.getDefaultInstance()) return this;
      if (!other.getDataXName().isEmpty()) {
        dataXName_ = other.dataXName_;
        onChanged();
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (other.getNext() != false) {
        setNext(other.getNext());
      }
      internalGetMutableOrderByCols().mergeFrom(
          other.internalGetOrderByCols());
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object dataXName_ = "";
    /**
     * <code>string dataXName = 1;</code>
     */
    public java.lang.String getDataXName() {
      java.lang.Object ref = dataXName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataXName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataXName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataXNameBytes() {
      java.lang.Object ref = dataXName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataXName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataXName = 1;</code>
     */
    public Builder setDataXName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataXName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataXName = 1;</code>
     */
    public Builder clearDataXName() {
      
      dataXName_ = getDefaultInstance().getDataXName();
      onChanged();
      return this;
    }
    /**
     * <code>string dataXName = 1;</code>
     */
    public Builder setDataXNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataXName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <code>string tableName = 2;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableName = 2;</code>
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 2;</code>
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 2;</code>
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private boolean next_ ;
    /**
     * <code>bool next = 3;</code>
     */
    public boolean getNext() {
      return next_;
    }
    /**
     * <code>bool next = 3;</code>
     */
    public Builder setNext(boolean value) {
      
      next_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool next = 3;</code>
     */
    public Builder clearNext() {
      
      next_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> orderByCols_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetOrderByCols() {
      if (orderByCols_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OrderByColsDefaultEntryHolder.defaultEntry);
      }
      return orderByCols_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableOrderByCols() {
      onChanged();;
      if (orderByCols_ == null) {
        orderByCols_ = com.google.protobuf.MapField.newMapField(
            OrderByColsDefaultEntryHolder.defaultEntry);
      }
      if (!orderByCols_.isMutable()) {
        orderByCols_ = orderByCols_.copy();
      }
      return orderByCols_;
    }

    public int getOrderByColsCount() {
      return internalGetOrderByCols().getMap().size();
    }
    /**
     * <pre>
     * 主键值，如果是首次查询，可以不设置该值
     * </pre>
     *
     * <code>map&lt;string, string&gt; orderByCols = 4;</code>
     */

    public boolean containsOrderByCols(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetOrderByCols().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOrderByColsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getOrderByCols() {
      return getOrderByColsMap();
    }
    /**
     * <pre>
     * 主键值，如果是首次查询，可以不设置该值
     * </pre>
     *
     * <code>map&lt;string, string&gt; orderByCols = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getOrderByColsMap() {
      return internalGetOrderByCols().getMap();
    }
    /**
     * <pre>
     * 主键值，如果是首次查询，可以不设置该值
     * </pre>
     *
     * <code>map&lt;string, string&gt; orderByCols = 4;</code>
     */

    public java.lang.String getOrderByColsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOrderByCols().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 主键值，如果是首次查询，可以不设置该值
     * </pre>
     *
     * <code>map&lt;string, string&gt; orderByCols = 4;</code>
     */

    public java.lang.String getOrderByColsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOrderByCols().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearOrderByCols() {
      internalGetMutableOrderByCols().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 主键值，如果是首次查询，可以不设置该值
     * </pre>
     *
     * <code>map&lt;string, string&gt; orderByCols = 4;</code>
     */

    public Builder removeOrderByCols(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableOrderByCols().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableOrderByCols() {
      return internalGetMutableOrderByCols().getMutableMap();
    }
    /**
     * <pre>
     * 主键值，如果是首次查询，可以不设置该值
     * </pre>
     *
     * <code>map&lt;string, string&gt; orderByCols = 4;</code>
     */
    public Builder putOrderByCols(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableOrderByCols().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * 主键值，如果是首次查询，可以不设置该值
     * </pre>
     *
     * <code>map&lt;string, string&gt; orderByCols = 4;</code>
     */

    public Builder putAllOrderByCols(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableOrderByCols().getMutableMap()
          .putAll(values);
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>uint32 pageSize = 5;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>uint32 pageSize = 5;</code>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 pageSize = 5;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stream.PreviewRowsDataCriteria)
  }

  // @@protoc_insertion_point(class_scope:stream.PreviewRowsDataCriteria)
  private static final com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria();
  }

  public static com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PreviewRowsDataCriteria>
      PARSER = new com.google.protobuf.AbstractParser<PreviewRowsDataCriteria>() {
    @java.lang.Override
    public PreviewRowsDataCriteria parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PreviewRowsDataCriteria(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PreviewRowsDataCriteria> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreviewRowsDataCriteria> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qlangtech.tis.rpc.grpc.datax.preview.PreviewRowsDataCriteria getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

