// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public interface PreviewRowsDataCriteriaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.PreviewRowsDataCriteria)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataXName = 1;</code>
   */
  java.lang.String getDataXName();
  /**
   * <code>string dataXName = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataXNameBytes();

  /**
   * <code>string tableName = 2;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string tableName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>bool next = 3;</code>
   */
  boolean getNext();

  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>repeated .stream.OffsetColValGrpc orderByCols = 4;</code>
   */
  java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.OffsetColValGrpc> 
      getOrderByColsList();
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>repeated .stream.OffsetColValGrpc orderByCols = 4;</code>
   */
  com.qlangtech.tis.rpc.grpc.datax.preview.OffsetColValGrpc getOrderByCols(int index);
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>repeated .stream.OffsetColValGrpc orderByCols = 4;</code>
   */
  int getOrderByColsCount();
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>repeated .stream.OffsetColValGrpc orderByCols = 4;</code>
   */
  java.util.List<? extends com.qlangtech.tis.rpc.grpc.datax.preview.OffsetColValGrpcOrBuilder> 
      getOrderByColsOrBuilderList();
  /**
   * <pre>
   * 主键值，如果是首次查询，可以不设置该值
   * </pre>
   *
   * <code>repeated .stream.OffsetColValGrpc orderByCols = 4;</code>
   */
  com.qlangtech.tis.rpc.grpc.datax.preview.OffsetColValGrpcOrBuilder getOrderByColsOrBuilder(
      int index);

  /**
   * <code>uint32 pageSize = 5;</code>
   */
  int getPageSize();
}
