// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stream.StringValue colVals = 1;</code>
   */
  java.util.List<com.qlangtech.tis.rpc.grpc.datax.preview.StringValue> 
      getColValsList();
  /**
   * <code>repeated .stream.StringValue colVals = 1;</code>
   */
  com.qlangtech.tis.rpc.grpc.datax.preview.StringValue getColVals(int index);
  /**
   * <code>repeated .stream.StringValue colVals = 1;</code>
   */
  int getColValsCount();
  /**
   * <code>repeated .stream.StringValue colVals = 1;</code>
   */
  java.util.List<? extends com.qlangtech.tis.rpc.grpc.datax.preview.StringValueOrBuilder> 
      getColValsOrBuilderList();
  /**
   * <code>repeated .stream.StringValue colVals = 1;</code>
   */
  com.qlangtech.tis.rpc.grpc.datax.preview.StringValueOrBuilder getColValsOrBuilder(
      int index);
}
