// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preview-datax-records.proto

package com.qlangtech.tis.rpc.grpc.datax.preview;

public interface StringValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.StringValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();

  /**
   * <code>bool nil = 2;</code>
   */
  boolean getNil();
}
